name: 功能建议
description: 提议一个具体使用场景
title: "[Feature] "
labels: [enhancement]
body:
  - type: textarea
    id: scenario
    attributes:
      label: 使用场景
      description: 你希望完成什么任务？
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: 建议方案
  - type: textarea
    id: alternatives
    attributes:
      label: 可选方案
